# Generated by Django 3.1 on 2020-12-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_article_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='twitter_data',
            field=models.JSONField(default=dict),
        ),
    ]
