# Generated by Django 5.2.2 on 2026-08-04 09:05

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, Max


def deduplicate_reviews(apps, schema_editor):
    Review = apps.get_model("api", "Review")
    duplicates = (
        Review.objects.values("user_id", "article_id")
        .annotate(total=Count("id"), keep_id=Max("id"))
        .filter(total__gt=1)
    )
    for duplicate in duplicates.iterator():
        Review.objects.filter(
            user_id=duplicate["user_id"],
            article_id=duplicate["article_id"],
        ).exclude(id=duplicate["keep_id"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_article_twitter_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'verbose_name': 'author', 'verbose_name_plural': 'authors'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='add_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, to='api.authors'),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='identifiers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='pdf',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='twitter_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='authors',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='library',
            name='articles',
            field=models.ManyToManyField(blank=True, to='api.article'),
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Positive'), (-1, 'Negative')]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(blank=True, to='api.article'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-year'], name='article_year_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-add_on'], name='article_added_desc_idx'),
        ),
        migrations.RunPython(deduplicate_reviews, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='unique_user_article_review'),
        ),
    ]
