# Generated by Django 5.2.2 on 2026-08-04 09:30

import django.db.models.deletion
import re
import unicodedata
from django.db import migrations, models


def populate_normalized_titles(apps, schema_editor):
    Article = apps.get_model("api", "Article")
    whitespace = re.compile(r"\s+")
    batch = []
    for article in Article.objects.only("id", "title").iterator(chunk_size=1000):
        value = unicodedata.normalize("NFKC", article.title or "").casefold()
        value = "".join(
            character if character.isalnum() else " " for character in value
        )
        article.normalized_title = whitespace.sub(" ", value).strip()
        batch.append(article)
        if len(batch) == 1000:
            Article.objects.bulk_update(batch, ["normalized_title"])
            batch = []
    if batch:
        Article.objects.bulk_update(batch, ["normalized_title"])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_authors_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cited_identifier', models.CharField(max_length=255)),
                ('identifier_scheme', models.CharField(max_length=32)),
                ('source', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('external_id', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('payload_checksum', models.CharField(max_length=64)),
                ('retrieved_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=255)),
                ('normalized_value', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='arxiv_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='citation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='doi',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_open_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='is_retracted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='normalized_title',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='openalex_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='reference_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='semantic_scholar_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='venue',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(condition=models.Q(('doi__isnull', False)), fields=('doi',), name='unique_article_doi'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(condition=models.Q(('arxiv_id__isnull', False)), fields=('arxiv_id',), name='unique_article_arxiv_id'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(condition=models.Q(('openalex_id__isnull', False)), fields=('openalex_id',), name='unique_article_openalex_id'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(condition=models.Q(('semantic_scholar_id__isnull', False)), fields=('semantic_scholar_id',), name='unique_article_s2_id'),
        ),
        migrations.AddField(
            model_name='citation',
            name='cited_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_citations', to='api.article'),
        ),
        migrations.AddField(
            model_name='citation',
            name='citing_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_citations', to='api.article'),
        ),
        migrations.AddField(
            model_name='sourcerecord',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_records', to='api.article'),
        ),
        migrations.AddField(
            model_name='workidentifier',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_identifiers', to='api.article'),
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.UniqueConstraint(fields=('citing_article', 'identifier_scheme', 'cited_identifier'), name='unique_article_citation'),
        ),
        migrations.AddIndex(
            model_name='sourcerecord',
            index=models.Index(fields=['source', 'external_id'], name='source_record_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcerecord',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_source_record'),
        ),
        migrations.AddIndex(
            model_name='workidentifier',
            index=models.Index(fields=['scheme', 'normalized_value'], name='work_identifier_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='workidentifier',
            constraint=models.UniqueConstraint(fields=('scheme', 'normalized_value'), name='unique_normalized_work_identifier'),
        ),
        migrations.RunPython(populate_normalized_titles, migrations.RunPython.noop),
    ]
