# Generated by Django 5.2.2 on 2026-08-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_metadataenrichmentattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(db_index=True, max_length=32)),
                ("external_id", models.CharField(max_length=255)),
                (
                    "version_type",
                    models.CharField(db_index=True, default="unknown", max_length=32),
                ),
                (
                    "version_label",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                (
                    "landing_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "pdf_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "arxiv_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("is_open_access", models.BooleanField(default=False)),
                (
                    "license",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "host_type",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "oa_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("provenance", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="api.article",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["article", "version_type"],
                        name="work_version_article_type_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "external_id"),
                        name="unique_source_work_version",
                    )
                ],
            },
        ),
    ]
