# Generated by Django 5.2.2 on 2026-08-08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_retrieval_evaluation"),  # gitleaks:allow
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # gitleaks:allow
    ]

    operations = [
        migrations.AddField(
            model_name="retrievalevent",
            name="actor_digest",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="ExperimentProtocol",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("version", models.PositiveSmallIntegerField()),
                ("spec_sha256", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("status", models.CharField(db_index=True, default="frozen", max_length=16)),
                ("frozen_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RetrievalInteraction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("document_id", models.CharField(max_length=100)),
                ("event_type", models.CharField(choices=[("impression", "Impression"), ("click", "Click"), ("save", "Save"), ("relevance", "Relevance feedback")], db_index=True, max_length=16)),
                ("rank", models.PositiveSmallIntegerField()),
                ("relevance", models.SmallIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("article", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="retrieval_interactions", to="api.article")),
                ("retrieval_event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="interactions", to="api.retrievalevent")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="retrieval_interactions", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(model_name="experimentprotocol", constraint=models.UniqueConstraint(fields=("name", "version"), name="unique_experiment_protocol_version")),
        migrations.AddConstraint(model_name="retrievalinteraction", constraint=models.UniqueConstraint(fields=("retrieval_event", "document_id", "event_type"), name="unique_retrieval_document_interaction")),
        migrations.AddConstraint(model_name="retrievalinteraction", constraint=models.CheckConstraint(condition=models.Q(("relevance__isnull", True), ("relevance__in", [-1, 1]), _connector="OR"), name="valid_retrieval_relevance_value")),
        migrations.AddIndex(model_name="retrievalinteraction", index=models.Index(fields=["event_type", "-created_at"], name="retrieval_interaction_type_idx")),
    ]
