# Generated by Django 5.2.2 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("api", "0017_retrieval_interactions_protocol")]

    operations = [
        migrations.AddField(
            model_name="retrievalevent",
            name="deployment_version",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="retrievalevent",
            name="protocol_sha256",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
    ]
