# Generated by Django 5.2.2 on 2026-08-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_retrieval_event_reproducibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrievalevent',
            name='expansion_cache_hit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='retrievalevent',
            name='expansion_cached_input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='retrievalevent',
            name='expansion_estimated_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='retrievalevent',
            name='expansion_input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='retrievalevent',
            name='expansion_latency_ms',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='retrievalevent',
            name='expansion_output_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='retrievalevent',
            name='expansion_prompt_version',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='retrievalevent',
            name='expansion_provider_response_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
